### ISSUE TITLE
Performance screenshots look weird

### ISSUE THREAD

**Issue by vwxyzjn** [zplizzi/pytorch-ppo#1]
![IMG_0159](https://user-images.githubusercontent.com/5555347/66346706-b9fb7300-e920-11e9-812e-ae29b2d2f0f2.png)

**Comment by zplizzi** [comment]
They're histograms of the episode returns. So if we're running 100 rollouts in parallel, each will have a different score. You could just plot the mean of all these scores, but plotting the histogram shows some additional interesting information - in this case, you can see that the scores are bimodal after step 400 - some episodes do pretty poorly, but others are doing pretty well (and there's not much in between).

**Comment by vwxyzjn** [comment]
@zplizzi I see. Thanks for the comment.
